# application-prod.yml
server:
  port: ${SERVER_PORT:19200}

spring:
  application:
    name: waiting-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: waiting-service
        format_sql: true
    show-sql: true

  cloud:                # 10.으로 시작하는 ip가 유레카에 우선 등록되도록, 다른 서비스가 찾을 수 있도록
    inetutils:
      ignored-interfaces:
        - "lo"
        - "docker.*"
        - "veth.*"
      preferred-networks:
        - "10.0"           # 본인 VPC CIDR 첫 두 옥텟
      use-only-site-local-interfaces: true

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true

management:              # actuator
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
