spring:
  application:
    name: waiting-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 19200

waiting:
  activate-ratio: 0.1
  activate-scheduler-delay-ms: 10000
  expire-scheduler-delay-ms: 10000
  expire-minutes: 10
